- title: fumigatus het genes
    cite:
        id: 10.1093/molbev/msae079

- title: agaricus incompatibility
    cite:
        id: doi:10.1101/2025.08.15.670591

- title: schimmelradar
    cite:
        id: 10.1093/ismejo/wraf246
